channels:
  - conda-forge
  - bioconda
dependencies:
  # renovate: datasource=conda depName=bioconda/htslib
  - bioconda::htslib=1.20
  # renovate: datasource=conda depName=bioconda/samtools
  - bioconda::samtools=1.20
