# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "h5ad_ambient_removal"
description: Ambient RNA removal from AnnData (h5ad) files
keywords:
  - single-cell
  - scRNA-seq
  - ambient RNA removal
components:
  - celda/decontx
  - cellbender/removebackground
  - cellbender/merge
  - soupx
  - scvitools/scar
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - ch_filtered_unfiltered:
      type: file
      description: |
        List of input h5ad files (size 2) containing filtered and unfiltered h5ad files
  - tool:
      type: string
      description: |
        Tool to use for ambient RNA removal.
        Allowed values: ["none", "decontx", "cellbender", "soupx", "scar"]
output:
  - h5ad:
      type: file
      description: |
        h5ad file containing ambient RNA removed counts as `adata.X`
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@nictru"
maintainers:
  - "@nictru"
