name: bowtie2_align
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # renovate: datasource=conda depName=bioconda/bowtie2
  - bowtie2=2.5.2
  # renovate: datasource=conda depName=bioconda/samtools
  - samtools=1.18
  # renovate: datasource=conda depName=conda-forge/pigz
  - pigz=2.6
