# TODO Change to Wave
name: Generate conda-lock
# When environment.yml is changed
on:
  pull_request:
    paths:
      - "**/environment.yml"

env:
  WAVE_VER: "1.4.1"

jobs:
  gen-matrix:
    name: generate-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Calculate file differences
        id: diff
        uses: tj-actions/changed-files@v44
        with:
          json: true
          quotepath: false
          # TODO Add Dockerfiles
          files: |
            modules/**/environment.yml
      - name: Debug
        run: echo ${{ steps.diff.outputs.all_changed_files }}
      - id: set-matrix
        run: echo "matrix={\"profile\":[\"docker\", \"singularity\"],\"files\":${{ steps.diff.outputs.all_changed_files }} }" >> "$GITHUB_OUTPUT"

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    if: "${{ fromJson(needs.gen-matrix.outputs.matrix) }}"
    needs: gen-matrix
    name: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix: "${{ fromJson(needs.gen-matrix.outputs.matrix) }}"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: weiji14/conda-lock-refresh@main
        with:
          file: "${{ matrix.files }}"
          # TODO platform: ["linux-64", "osx-arm64"]

      # Action runs on the issue comment, so we don't get the PR by default
      # Use the gh cli to check out the PR
      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.nf_core_bot_auth_token }}

      - name: Commit condalock files to PR
        run: |
          if [[ $(git ls-files --modified --others) ]]; then
            git config --global user.name 'actions-bot'
            git config --global user.email '58130806+actions-bot@users.noreply.github.com'
            git add --all
            git commit --message "[condalock-command] autogenerated conda-lock files"
            git push
          fi
        shell: bash -l {0}

      - name: Get the lock file path
        uses: actions/github-script@v7
        id: lockfile-name
        with:
          result-encoding: string
          script: |
            return '${{ matrix.files }}'.replace('/environment.yml', '/conda-lock.yml');

        # TODO Build containers with Wave
